

import java.util.Calendar;
import java.util.Random;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lab803
 */
public class AppWhats extends javax.swing.JFrame {

    /**
     * Creates new form AppWhats
     */
    //Felipe Lima   RA:20935803
    //Pedro Messias RA:20937489
    
    WhatsApp wpp;
    Vector<String> contatos = new Vector();
    Calendar online = Calendar.getInstance();
    int random;
    ArquivoSerializadoWhats asw = new ArquivoSerializadoWhats("whats.txt");
    
    
    public AppWhats() {
        initComponents();
        wpp = asw.lerArquivo();
        
        Random r = new Random();
        random = r.nextInt(4);
        for (int i = 0; i < wpp.getListaConversa().size(); i++) {
               contatos.add(wpp.getListaConversa().get(i).getContato());
               listContatos.setListData(contatos); 
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoVoceContato = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listContatos = new javax.swing.JList<>();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnNovaMensagem = new javax.swing.JButton();
        txtMensagem = new javax.swing.JTextField();
        rbVoce = new javax.swing.JRadioButton();
        rbContato = new javax.swing.JRadioButton();
        btnEnviar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaConversas = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaInformacao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNome.setText("Seu Nome");

        lblStatus.setText("Seu Status");

        listContatos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listContatosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listContatos);

        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnNovaMensagem.setText("NOVA MSG");
        btnNovaMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaMensagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(txtPesquisar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovaMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnNovaMensagem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        grupoVoceContato.add(rbVoce);
        rbVoce.setText("Você");

        grupoVoceContato.add(rbContato);
        rbContato.setText("Contato");

        btnEnviar.setText("ENVIAR");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        areaConversas.setColumns(20);
        areaConversas.setRows(5);
        jScrollPane4.setViewportView(areaConversas);

        areaInformacao.setColumns(20);
        areaInformacao.setRows(5);
        jScrollPane5.setViewportView(areaInformacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMensagem)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbVoce)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbContato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbVoce)
                    .addComponent(rbContato)
                    .addComponent(btnEnviar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        //Seta o nome e o status do Usuario
        switch(random){
            case 1:
                lblStatus.setText("Disponível");
                break;
            case 2:
                lblStatus.setText("Ausente");
                break;
            case 3:
                lblStatus.setText("Ocupado");
                break;
            default:
                lblStatus.setText("Jogando LOL");
        }
        lblNome.setText(wpp.getNomeUsuario()+" - "+wpp.getTelUsuario());
        
    }//GEN-LAST:event_formWindowActivated

    private void btnNovaMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaMensagemActionPerformed
        // TODO add your handling code here:
        
        //Cria uma nova conversa com um contato e adiciona ele na JList
        String telContato = JOptionPane.showInputDialog("Digite o Telefone/Nome do Contato");
        for (int i = 0; i <wpp.getListaConversa().size(); i++) {
            if(wpp.getListaConversa().get(i).getContato().equalsIgnoreCase(telContato)){
                JOptionPane.showMessageDialog(null, "Essse contato já foi adicionado"
                        ,"Erro",JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        wpp.iniciarConversa(telContato);
        contatos.add(wpp.toString());
        listContatos.setListData(contatos);
    }//GEN-LAST:event_btnNovaMensagemActionPerformed

    private void listContatosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listContatosValueChanged
        // TODO add your handling code here:
        
        //Exibe a conversa com o contato selecionado e também suas informações
        if(listContatos.getSelectedIndex()!=-1){
            String vistoUltimo;
        if(wpp.buscarContatoDois(listContatos.getSelectedValue()).getOnline().get(Calendar.MINUTE)<10){
            vistoUltimo = "Visto por último as: "+wpp.buscarContatoDois(listContatos.getSelectedValue()).getOnline().get(Calendar.HOUR_OF_DAY)
                    +":0"+wpp.buscarContatoDois(listContatos.getSelectedValue()).getOnline().get(Calendar.MINUTE);
        }else{
            vistoUltimo = "Visto por último as: "+wpp.buscarContatoDois(listContatos.getSelectedValue()).getOnline().get(Calendar.HOUR_OF_DAY)
                    +":"+wpp.buscarContatoDois(listContatos.getSelectedValue()).getOnline().get(Calendar.MINUTE);
        }
            areaConversas.setText("As mensagens são criptografadas\n"+wpp.buscarContato(listContatos.getSelectedValue()));
            areaInformacao.setText(wpp.buscarContatoDois(listContatos.getSelectedValue()).getContato()+"\n"+vistoUltimo);
        }
    }//GEN-LAST:event_listContatosValueChanged

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        
        //Envia ou recebe uma mensagem e atualiza a conversa
        if(rbVoce.isSelected()){
            if(listContatos.getSelectedIndex()!=-1){
                for (int i = 0; i < wpp.buscarContatoDois(listContatos.getSelectedValue()).getListaMensagem().size(); i++) {
                    wpp.buscarContatoDois(listContatos.getSelectedValue()).getListaMensagem().get(i).setStatus("foi lida");
                }
                wpp.buscarContatoDois(listContatos.getSelectedValue()).adicionarMensagem(wpp.getNomeUsuario(), txtMensagem.getText());
                areaConversas.setText("As mensagens são criptografadas\n"+wpp.buscarContato(listContatos.getSelectedValue()));
            }
        }
        if(rbContato.isSelected()){
            if(listContatos.getSelectedIndex()!=-1){
                for (int i = 0; i < wpp.buscarContatoDois(listContatos.getSelectedValue()).getListaMensagem().size(); i++) {
                    wpp.buscarContatoDois(listContatos.getSelectedValue()).getListaMensagem().get(i).setStatus("foi lida");
                }
                online = Calendar.getInstance();
                wpp.buscarContatoDois(listContatos.getSelectedValue()).adicionarMensagem(wpp.buscarContatoTres(listContatos.getSelectedValue()), txtMensagem.getText());
                wpp.buscarContatoDois(listContatos.getSelectedValue()).setOnline(online);
                areaConversas.setText("As mensagens são criptografadas\n"+wpp.buscarContato(listContatos.getSelectedValue()));
            }
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        
        //Pesquisa uma palavra na conversa selecionada
         String pesquisa = txtPesquisar.getText();
         if(listContatos.getSelectedIndex()!=-1){
            
            JOptionPane.showMessageDialog(null, wpp.buscarContatoDois(listContatos.getSelectedValue()).buscarPalavra(pesquisa).toString()
                        ,"Resultado",JOptionPane.INFORMATION_MESSAGE);
            }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        asw.gravarArquivo(wpp);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppWhats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppWhats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppWhats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppWhats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppWhats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaConversas;
    private javax.swing.JTextArea areaInformacao;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnNovaMensagem;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.ButtonGroup grupoVoceContato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList<String> listContatos;
    private javax.swing.JRadioButton rbContato;
    private javax.swing.JRadioButton rbVoce;
    private javax.swing.JTextField txtMensagem;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
